### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by Infernalino** [NotDaymon/ROBLOXIPPuller#1]
When i open the folder, there is a option named App. When I try to open it, it says choose an app to open. And when I check the file properties, its a config file. Welp

**Comment by daymxn** [comment]
`Program.cs` is the entry point for the application. 
Additionally, this project is four years old- I'm unsure if even still works.

**Comment by Infernalino** [comment]
When I open the Program.cs file it opens a text doc file. HOw do I run the
app?

**Comment by daymxn** [comment]
> When I open the Program.cs file it opens a text doc file. HOw do I run the app?
> […](#)

This is the source code for the application, you have to build it in any C# compiler (ie; visual studio)

**Comment by Infernalino** [comment]
Do you have some kind of tutorial or something?
