### ISSUE TITLE
Unable to build -  Specify a project or solution file. The current working directory does not contain a project or solution file.

### ISSUE THREAD

**Issue by FxllenCode** [NotDaymon/ROBLOXIPPuller#2]
## Major Disclaimer: 

Never built a C# application before, so I'm probably doing something wrong.

I've installed .NET and attempted to build via VS Code, however it always leaves me with that error message.

Help would be appreciated! Thank you.

**Comment by daymxn** [comment]
> ## Major Disclaimer:
> Never built a C# application before, so I'm probably doing something wrong.
> 
> I've installed .NET and attempted to build via VS Code, however it always leaves me with that error message.
> 
> Help would be appreciated! Thank you.

Ensure that you're working and building with the **RobloxIPFinder.sln** as your root solution. Also make sure your .NET version lines up with the program. There may be some unaddressed compatibility issues- seeing as this project is 5 years old.

**Comment by FxllenCode** [comment]
Hey @NotDaymon, thanks for the help! 

It still seems I'm getting the errors upon building the application, would you be kind enough to compile the program and include it into the repo as a .exe? Thanks a bunch!
